"use client";

import { useCallback, useEffect, useState } from "react";
import { AppNav } from "../../components/app-nav";
import { supabase } from "../../lib/supabase";

type SecurityData = { blocked: Array<{ email: string; message: string; block_reason: string | null; created_at: string }>; topUsers: Array<{ email: string; today: number; week: number; percent: number }>; alerts: Array<{ type: string; text: string }>; stats: { totalToday: number; totalWeek: number; blockedCount: number; averagePerUser: number } };
const number = (value: number) => value.toLocaleString("pl-PL");

export default function SecurityPage() {
  const [data, setData] = useState<SecurityData | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); if (!supabase) { setError("Brak konfiguracji Supabase."); setLoading(false); return; } const { data: sessionData } = await supabase.auth.getSession(); const token = sessionData.session?.access_token; if (!token) { setError("Zaloguj się jako administrator."); setLoading(false); return; } const response = await fetch("/api/admin/security", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Nie udało się pobrać panelu."); else setData(payload); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const stats = data?.stats;
  const cards = stats ? [["!", "danger", "Podejrzane wiadomości", stats.blockedCount, "ostatnie 24h"], ["×", "warning", "Zablokowane zadania", stats.blockedCount, "ochrona aktywna"], ["T", "info", "Zużyte tokeny", number(stats.totalToday), "ostatnie 24h"], ["◆", "purple", "Aktywne alerty", data.alerts.length, "wymagają uwagi"]] : [];
  return <main className="page page-scroll app-page"><AppNav /><section className="security-shell"><header className="security-hero"><div><p>Panel administratora</p><h1>Centrum bezpieczeństwa</h1><span>Monitoring zagrożeń, limitów i wykorzystania AI z ostatnich 24 godzin.</span></div><div className="security-hero-actions"><span className="security-status"><i /> Monitoring aktywny</span><button type="button" onClick={() => void load()} disabled={loading}>{loading ? "Odświeżam…" : "↻ Odśwież dane"}</button></div></header>{error ? <div className="empty-state"><p>{error}</p></div> : loading && !data ? <div className="empty-state"><p>Ładuję dane bezpieczeństwa…</p></div> : data ? <><section className="security-metrics">{cards.map(([icon, tone, label, value, note]) => <article className="security-metric" key={String(label)}><span className={`security-icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</section><section className="security-summary-grid"><article className="security-panel"><div className="security-panel-heading"><div><p>Sygnały</p><h2>Alerty</h2></div><b>{data.alerts.length}</b></div>{data.alerts.length ? <div className="security-alert-list">{data.alerts.map((alert, index) => <p key={index}><span>✓</span><strong>{alert.type}</strong><br />{alert.text}</p>)}</div> : <div className="security-empty"><span>✓</span><strong>Brak aktywnych zagrożeń</strong><p>W ostatnich 24 godzinach nie wykryto zdarzeń wymagających uwagi.</p></div>}</article><article className="security-panel"><div className="security-panel-heading"><div><p>Wykorzystanie</p><h2>Top 5 użytkowników</h2></div><small>tokeny / 24h</small></div>{data.topUsers.length ? <div className="security-user-list">{data.topUsers.map((user) => <div key={user.email}><span>{user.email}</span><strong>{number(user.today)} <small>({user.percent}%)</small></strong></div>)}</div> : <div className="security-empty"><span>⌁</span><strong>Brak zarejestrowanego zużycia</strong><p>Wykorzystanie tokenów pojawi się po rozmowach z agentem.</p></div>}</article></section><section className="security-panel security-events"><div className="security-panel-heading"><div><p>Dziennik zdarzeń</p><h2>Podejrzane wiadomości i blokady</h2></div><span className="security-filter">Wszystkie</span></div>{data.blocked.length ? <div className="security-event-list">{data.blocked.map((item, index) => <article key={`${item.created_at}-${index}`}><span className="security-event-icon">!</span><div><strong>{item.email}</strong><p>{item.message.slice(0, 180)}{item.message.length > 180 ? "…" : ""}</p><small>{item.block_reason ?? "Blokada bezpieczeństwa"} · {new Date(item.created_at).toLocaleString("pl-PL")}</small></div></article>)}</div> : <div className="security-empty security-empty-large"><span>✓</span><strong>Brak zdarzeń dla wybranego filtra</strong><p>Ochrona działa, a dziennik jest czysty.</p></div>}</section></> : null}</section></main>;
}
